### ISSUE TITLE
[FEAT]: Practice CD

### ISSUE THREAD

**Issue by hoang-himself** [Smithienious/dotfiles#11]
### Description

Completes [Build, release, run](https://github.com/Smithienious/Smithienious/blob/main/README.md?plain=1#L50)

Trigger CD only on tags

```yml
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'           # Push events to every tag not containing /
```

```yml
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**'           # Push events to every tag including hierarchical tags like v1.0/beta
```

[SO answer](https://stackoverflow.com/a/61892639/15142953)
